Rework on the listener
updatehub/agent-sdk-go pull request #12
Opened 2020-10-22 21:41 UTC by Asakiz

Also added documentation for the listener.

Signed-off-by: asakiz <asakizin@gmail.com>

2020-10-23 02:23 UTC, otavio requested changes
Please organize the commits so we can go for merging it.

2020-10-23 02:23 UTC, otavio commented on .github/workflows/ci.yml
> +      - v2
Split in a specific commit.

2020-10-24 00:16 UTC, otavio approved these changes

2020-10-24 00:18 UTC, otavio commented
What else is need for this to be ready for merge?

2020-10-24 02:13 UTC, Asakiz commented
For now, nothing. Is ready to merge.

2020-10-24 13:01 UTC, merged